import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/authContext";
import { PostProvider } from "./context/postsContext";
import ChatProvider from "./context/ChatProvider";
import { ChakraProvider } from "@chakra-ui/react";
import "./layout.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`Layout ${inter.className}`}>
        <ChakraProvider>
          <AuthProvider>
            <PostProvider>
              <ChatProvider>
                <ChakraProvider>{children}</ChakraProvider>
              </ChatProvider>
            </PostProvider>
          </AuthProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
